language: cpp
dist: xenial
matrix:
  include:
  - os: linux
    env: PYTHON=3.7
  - os: linux
    env: PYTHON=3.8
before_install:
- |
  export CXX=g++-5.4 CC=gcc-5.4
  sudo apt-get install libeigen3-dev
  pip3 install --user --upgrade pip virtualenv
  virtualenv -p python$PYTHON venv
  source venv/bin/activate
install:
- |
  pip install -e -v .
  pip install tox
script:
  - tox -v -e py
