# Inspiration: https://github.com/pybind/cmake_example/blob/master/.travis.yml
language: cpp

dist: bionic

matrix:
  include:
  - os: linux
    env: PYTHON=3.6
    addons:
      apt:
        update: true
        packages:
          - libeigen3-dev python3-pip python3.6-dev
  - os: linux
    env: PYTHON=3.7
    addons:
      apt:
        update: true
        packages:
          - libeigen3-dev python3-pip python3.7-dev
  - os: linux
    env: PYTHON=3.8
    addons:
      apt:
        update: true
        packages:
          - libeigen3-dev python3-pip python3.8-dev
  - os: osx
    env: PYTHON=3
    addones:
      homebrew:
        update: true
        packages:
          - python3

before_install:
- |
  python3 -m pip install --upgrade virtualenv
  virtualenv -p python$PYTHON venv
  source venv/bin/activate

install:
- |
  python setup.py sdist
  pip install --verbose dist/*.tar.gz
  pip install pytest pytest-approvaltests pytest-flake8 coverage

script:
- |
  coverage run --omit 'venv/*' -m pytest -s --ignore=lib
  pytest -s --ignore=lib --flake8

after_success:
  - bash <(curl -s https://codecov.io/bash)
